server:
  port: 60000
spring:
  config:
    import: optional:configserver:http://127.0.0.1:8888/
  cloud:
    config:
      #      name: ecommerce
      name: user-service
  application:
    name: user-service
security:
  hmacKey: ZCj6NxuDt0jyq946B4M9TiIej