server:
  port: 8000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://fluffit.shop:8761/

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        #member-service
        - id: auth
          predicates:
            - Path=/auth/**
          uri: lb://MEMBER-SERVICE
        - id: member
          predicates:
            - Path=/member/**
          uri: lb://MEMBER-SERVICE
          filters:
            - CustomFilter

  data:
    redis:
      host: fluffit.shop
      port: 6379
      password: gumid204

#redis:
#  host: fluffit.shop
#  port: 6379
#  password: gumid204

management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: shutdown

